name: sampl_work
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  azlistview: ^2.0.0
  cupertino_icons: ^1.0.5
  flutter_native_splash: ^2.2.7
  font_awesome_flutter: ^10.1.0
  flutter:
    sdk: flutter
  get: 4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/tempo.png
  android_gravity: center

  android_12:
    image: assets/images/tempo.png
    icon_background_color: "#ffffff"

  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/

  fonts:
    - family: Josefin_Sans
      fonts:
        - asset: assets/fonts/Josefin_Sans/JosefinSans-Bold.ttf
        - asset: assets/fonts/Josefin_Sans/JosefinSans-Regular.ttf
